### PR TITLE
Add bootstrap

### PR DESCRIPTION
**Pull request by simonv3**
For Review Only

Started adding in bootstrap to step_16 for a prettier app.

screenshot 2015-03-31 10 37 31

### CODE REVIEW

**Comment by Urigo** [comment]
OK, but I've moved it to step 17 so please continue working on that there.
Also, I've created a text to step 17 you can edit if you want - https://github.com/Urigo/angular-meteor/blob/master/.docs/angular-meteor/client/views/steps/tutorial.step_17.html

There is still some work here I think but thank you so much for the help!

**Comment by simonv3** [comment]
That's awesome, that's what I figured this would be for. I agree, there's definitely still some work here, but I want to get as far as possible first with just using Bootstrap's styles, and not too much of our own styles.

**Comment by smoke** [comment]
Adding bootstrap was something I was about to ask - great job on doing this!

**Comment by Urigo** [comment]
@simonv3 it would be great to show at the beginning of the step just Bootstrap like you did, but then in the second part show how to use LESS to customize stuff (and also make to tutorial app look awesome as it deserves...)

**Pull request merged**
