### PR TITLE
step18 - enhancing  the login / register / reset windows look

### PR DESCRIPTION
**Pull request by Tallyb**
updating the look and feel. let me know if it works, or do I need to redo it

### CODE REVIEW

**Comment by Urigo** [comment]
@Tallyb I've pushed today a new version.
Also, to push your changes in with the new structure, maybe if better we will do it together in Hangouts

**Comment by Tallyb** [comment]
@Urigo  always a pleasure for me. If you want to see how the user screens will look like - check out http://angular-meteor-material.meteor.com/

**Comment by Urigo** [comment]
@Tallyb very cool but some things are not working for me.
1. Can't navigate to party details by clicking on the party
2. I need to click the checkbox a few times before it works
3. The "public" slider for each party is nice but then people also expect it to work

**Comment by Tallyb** [comment]
Yes, I am still looking into these 2 issues (and others...).
The todos app is aimed to be used as angular-meteor-material boilerplate, for those who like that trio, and need registration screens, etc. It has  my prefferred directory structure and I am further enhancing it. 

 Anyway, the pr was for the login / register / forgot password screens only. I am working also on the look and feel of socially step 18, but that will be separate pr.

**Comment by Urigo** [comment]
@simonv3 can you check out these login / register / forgot password screens?
maybe we can combine efforts here

**Comment by simonv3** [comment]
@Urigo I'll have a look, but I guess that what I've been working on doesn't use Material (and I'm actually thinking it makes sense to not give it very much design at all, so that whoever is building the website can style it appropriately).

**Comment by Urigo** [comment]
@Tallyb did I closed that??
I haven't meant to!
let's talk soon

**Comment by dotansimha** [comment]
Hi @Tallyb and @Urigo 
I was unable to merge it because I changed the history of the repo (needed some rebase to fix bugs).

So I took your commit and apply them manually :)

Thanks!

**Comment by Urigo** [comment]
Thanks @dotansimha !
@Tallyb can you review it please?

**Comment by Tallyb** [comment]
@dotansimha @Urigo 
what is the best tag / branch to check it on? 
also - I see that the assets are missing (3 svg icons under public). can you add them?

**Comment by dotansimha** [comment]
@Tallyb  @Urigo 
I think that something wrong with the SVG... my browser always blocks it... I fixed and added them in the 1.2 branch but it does not load it because the browser blocks the HTTP request... not sure why...

**Comment by Tallyb** [comment]
@dotansimha  stop using IE6! 
what error message on the http?

**Comment by dotansimha** [comment]
@Tallyb 
REQUEST_CANCELED or something like that... 
Also when I try to watch the SVG here in GitHub... same thing..
And I never use IE ! ! !

**Comment by Tallyb** [comment]
it was err_conn_refused. I got it for a sec. it seems to disappear when you remove cfs:graphicsmagick (which caused errored when I ran meteor).

**Comment by Urigo** [comment]
@Tallyb What about the new updated tutorial?

**Pull request closed without merging**
