### PR TITLE
merge to step_18

### PR DESCRIPTION
**Pull request by MilosStanic**
Sorry for late response, here it is.

### CODE REVIEW

**Comment by Urigo** [comment]
@MilosStanic looks like the change is not here...

**Comment by MilosStanic** [comment]
There already is a step_18 branch on your original repo. And it contains my changes. Why don't you merge it?

**Comment by Urigo** [comment]
@MilosStanic if step_18 already contains your changes then master contains them as well
Master is rebased against step_18

**Comment by MilosStanic** [comment]
yes, it does, I confirmed it. I'm closing this PR.

**Pull request closed without merging**
