### PR TITLE
Material login

### PR DESCRIPTION
**Pull request by MilosStanic**
@Urigo as we talked today (yesterday), here's the custom login/register/forgot password forms in angular-material. 

Please test and comment.

### CODE REVIEW

**Comment by Urigo** [comment]
Do you think it should go to step 18 or a separate step?

**Comment by MilosStanic** [comment]
Well, yes, it can go into step 18. Fits right into it. 
Only thing left to complete the transition to angular-material is to redo the pagination controls on the parties list page. And I really have no clue how to do it.

**Comment by Urigo** [comment]
@MilosStanic can you merge this into step_18 branch instead of the master?
thanks!

**Comment by Urigo** [comment]
@MilosStanic any updates?

**Pull request closed without merging**
